# Generated by Django 5.0.4 on 2026-05-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_articleimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleimage", old_name="artcle", new_name="article",
        ),
    ]
