# Generated by Django 5.0.4 on 2026-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_rename_artcle_articleimage_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
