# Generated by Django 5.0.4 on 2024-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
